// Code generated by tygo. DO NOT EDIT.
import { StructBar } from "../abstract";

//////////
// source: account.go

export interface User extends StructBar {
  Email: string;
}
export interface Account {
  Name: string;
  balance: number /* int64 */;
}
export interface AccountResponse extends Omit<Account & User, "balance"> {
}
